/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptotool.ui;

import java.awt.BorderLayout;
import java.awt.Container;

/**
 *
 * @author Samrand
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form CyrptoTool
     */
    public UserInterface() {
        initComponents();
        setTitle("CryptoTool");
        Container c = getContentPane();
        c.setLayout(new BorderLayout());
        c.add(new Home(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(400, 350));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("false"), this, org.jdesktop.beansbinding.BeanProperty.create("resizable"));
        bindingGroup.addBinding(binding);

        jMenuBar2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jMenu3.setText("Home");
        jMenu3.setMargin(new java.awt.Insets(0, 25, 0, 25));
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                navHome(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        jMenu4.setText("About");
        jMenu4.setMargin(new java.awt.Insets(0, 25, 0, 25));
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                navAbout(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu1.setText("Help");
        jMenu1.setMargin(new java.awt.Insets(0, 25, 0, 25));
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                navHelp(evt);
            }
        });
        jMenu1.add(jSeparator1);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navHome(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_navHome
        // TODO add your handling code here:
        javax.swing.JMenu temp = (javax.swing.JMenu)evt.getSource();
        temp.setSelected(false);
        setContentPane(new Home(this));
        invalidate();
        validate();
    }//GEN-LAST:event_navHome

    private void navAbout(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_navAbout
        // TODO add your handling code here:
        javax.swing.JMenu temp = (javax.swing.JMenu)evt.getSource();
        temp.setSelected(false);
        setContentPane(new About(this));
        invalidate();
        validate();
    }//GEN-LAST:event_navAbout

    private void navHelp(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_navHelp
        // TODO add your handling code here:
        javax.swing.JMenu temp = (javax.swing.JMenu)evt.getSource();
        temp.setSelected(false);
        setContentPane(new Help());
        invalidate();
        validate();
    }//GEN-LAST:event_navHelp

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
